# Generated by Django 6.1.1 on 2026-09-08 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_create_default_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("color", models.CharField(default="#ffffff", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PageTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.page")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tag")),
            ],
            options={
                "db_table": "pages_tags",
                "ordering": ["position", "tag__title"],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(fields=("user", "title"), name="unique_tag_title_per_user"),
        ),
        migrations.AddConstraint(
            model_name="pagetag",
            constraint=models.UniqueConstraint(fields=("page", "tag"), name="unique_tag_per_page"),
        ),
    ]
