# Generated by Django 6.1.1 on 2026-09-08 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tag_pagetag_tag_unique_tag_title_per_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=120, null=True)),
                ("url", models.URLField(max_length=2048)),
                ("favicon", models.URLField(max_length=2048, null=True)),
                ("notes", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "links",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TagLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.link")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tag")),
            ],
            options={
                "db_table": "tags_links",
                "ordering": ["position", "link__title"],
                "constraints": [models.UniqueConstraint(fields=("tag", "link"), name="unique_link_per_tag")],
            },
        ),
    ]
